@include('client.partials.program-database-partials.diet-week-plans._monday-plans')
@include('client.partials.program-database-partials.diet-week-plans._tuesday-plans')
@include('client.partials.program-database-partials.diet-week-plans._wednesday-plans')
@include('client.partials.program-database-partials.diet-week-plans._thursday-plans')
@include('client.partials.program-database-partials.diet-week-plans._thursday-plans')
@include('client.partials.program-database-partials.diet-week-plans._friday-plans')
@include('client.partials.program-database-partials.diet-week-plans._saturday-plans')
@include('client.partials.program-database-partials.diet-week-plans._sunday-plans')